language: android

jdk:
- oraclejdk8

os:
- linux

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28

before_cache:
- rm -f  ${HOME}/.gradle/caches/modules-2/modules-2.lock

cache:
  pip: true
  directories:
  - ${HOME}/.gradle/caches/
  - ${HOME}/.cache/pre-commit/
  - ${HOME}/.gradle/wrapper/
  - ${HOME}/.m2

script:
- ./gradlew preMerge

after_success:
- bash <(curl -s https://codecov.io/bash)
